Failover support
sumnerboy12/LSC pull request #15
Opened 2021-06-14 17:24 UTC by moinmoin-sh

Don't know if the merge will work, tells me "Can't automatically merge.  Don’t worry, you can still create the pull request. "
Don't understand Git .....

This is what I wanted to say : 

Here is a new proposal:

A few days ago there was a discussion on using the build-in HW invert function of the MCP.
I took a closer look and came to this proposal

The invert (polarity) function of the MCP can easily be activated. 
There is no need to do this at compile time (NO hard coding!). The invert bit can be set and reset on the fly (see new function MCPsetInvert()).

I see the following advantages:
utilize the HW that we have.
receiving the conf/invt message sets the invert bit in the MCP and it becomes active immediately
no bookkeeping of the invert variable required - like fire and forget.
saves resources (flash and ram)
the button code sees active input always as low
the port animation on the OLED shows active inputs always with the little square
there is no user observable difference to the sw solution 

What do you think

2021-06-14 21:27 UTC, sumnerboy12 requested changes
I agree with your comments - not sure it is any simpler in terms of coding, but it is simpler in terms of state we need to store/maintain and as you say, performs exactly the same function with less memory requirements.

2021-06-14 21:27 UTC, sumnerboy12 commented on Firmware/USMArduinoFirmware/USM_Input.cpp
>      // Default all inputs to buttons (non-inverted)
Fix comment

2021-06-14 21:27 UTC, sumnerboy12 commented on Firmware/USMArduinoFirmware/USMArduinoFirmware.ino
> +      MCPsetInvert(mcp, input, 0);
Could we rename this to `setMcpInvert()`? And maybe rename the `val` parameter to `invert` so it is clear what that is related to?

2021-06-14 21:27 UTC, sumnerboy12 commented on Firmware/USMArduinoFirmware/USMArduinoFirmware.ino
> +uint8_t MCPreadReg(int adr, uint8_t reg)
We already have `readRegister()` at the bottom of the sketch, for reading the MAC ROM register. I think we can modify that to pass the register address and use it for both the MAC and MCP register reads.

Then rename `MCPwriteReg` to `writeRegister()` to match the existing `readRegister()` naming format.

I.e. turn these into generic I2C register read/write helpers.

2021-06-14 21:28 UTC, sumnerboy12 commented
BTW - I have fixed the merge conflicts, which were caused by my pushing a few changes yesterday after you created your branch. In future if you want to avoid that sort of thing you need to rebase your PR branch to the branch you are wanting to merge to.

2021-06-15 07:03 UTC, moinmoin-sh commented
Thanks for your comments and suggestions. Wasn't sure if you would like it.
I'll take care for it a little later. Have plumbers coming in today and tomorrow.

2021-06-15 07:07 UTC, sumnerboy12 commented
I do kind of like the fact the inversion logic was encapsulated in the
USM_Input library, alongside the type config, but I can see the value in
using the h/w features on offer.

Plus the memory savings can't hurt!

On Tue, 15 Jun 2021, 19:03 moinmoin-sh, ***@***.***> wrote:

> Thanks for your comments and suggestions. Wasn't sure if you would like it.
> I'll take care for it a little later. Have plumbers coming in today and
> tomorrow.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sumnerboy12/LSC/pull/15#issuecomment-861236352>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGTR2XWQHZZACJ55KFRRB3TS33LXANCNFSM46VUXZRQ>
> .
>

2021-06-15 19:35 UTC, moinmoin-sh commented
I think I made the changes that you suggested.

Please check if the reading of the MAC-address rom still works - I don't have that HW

I made an addional change in the mqtt-callback. I think it's required to do a range check of the index in the topic because if that number is out of range a false mcp index would be calculated which leads to a write to a wrong address. That could cause weired behavior depending where the write goes.

2021-06-15 23:36 UTC, sumnerboy12 commented
I just pushed a couple of minor changes - everything worked fine on my test system but I just wanted to tidy up a few little bits. Thanks for the PR!

2021-06-15 23:36 UTC, merged